Fiorello/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Fiorello.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Fiorello/ViewComponents/HeaderViewComponent.cs
using Fiorello.DAL;
using Fiorello.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorello.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private AppDbContext _context;

        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<BasketViewModel> basket;
            if (Request.Cookies["basket"] != null)
            {
                basket = JsonConvert.DeserializeObject<List<BasketViewModel>>(Request.Cookies["basket"]);
                ViewBag.BasketItemCount = basket.Sum(p=>p.Count);
            }
            else
            {
                ViewBag.BasketItemCount = 0; 
            }
            var setting = _context.Settings
                                  .AsEnumerable()
                                  .ToDictionary(s => s.Key, s => s.Value);
            return  View(await Task.FromResult(setting));
        }
    }
}

Fiorello/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pushster&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    <link rel="icon" href="~/img/favicon.png" sizes="192x192" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/owlcarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/owlcarousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Fiorello &#8211; @ViewData["Title"]</title>
</head>

<body>
    @await Component.InvokeAsync("Header")
    @RenderBody()
    @await Component.InvokeAsync("Footer");
</body>

</html>

Fiorello/Views/Shared/_PaginatePartial.cshtml
<div class="table-pagination">

    <ul class="pagination justify-content-center">
        @if (Model.PageCount > 0)
        {
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index" asp-route-page="@(Model.CurrentPage-1)">
                        Previus
                    </a>
                </li>
                <li class="page-item" style="cursor:pointer">
                    <a class="page-link">
                        ...
                    </a>
                </li>
            }
            @for (int i = Model.StartPage; i <= Model.EndPage; i++)
            {
                <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-action="Index" asp-route-page="@i">
                        @i
                    </a>
                </li>
            }

            @if (Model.CurrentPage < Model.PageCount)
            {
                <li class="page-item" style="cursor:pointer">
                    <a class="page-link">
                        ...
                    </a>
                </li>
                <li class="page-item @(Model.CurrentPage == Model.PageCount ? "disabled" : "")">
                    <a class="page-link" asp-action="Index" asp-route-page="@(Model.CurrentPage+1)">
                        Next
                    </a>
                </li>
            }

        }
    </ul>
</div>

Fiorello/Views/Shared/_ProductPartial.cshtml
@model IEnumerable<Product> 
@foreach (var pro in Model)
{

    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
        <div class="product-item text-center">
            <div class="img">
                <a asp-action="Detail" asp-route-id="@pro.Id">
                    <img src="~/img/@pro.Images.Where(i=>i.IsMain==true).FirstOrDefault().Image" class="img-fluid" alt="">
                </a>
            </div>
            <div class="title mt-3">
                <h6>@pro.Name</h6>
            </div>
            <div class="price">
                <span class="text-black-50">Add to cart</span>
                <span class="text-black-50">$@pro.Price</span>
            </div>
        </div>

    </div>
}